# Generated by Django 2.1.3 on 2019-03-13 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='like',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='author_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
